Update blob_test.yml

diff --git a/.github/workflows/blob_test.yml b/.github/workflows/blob_test.yml
--- a/.github/workflows/blob_test.yml
+++ b/.github/workflows/blob_test.yml
@@ -28,3 +28,7 @@ jobs:
         run: |
           sudo blobfuse2 mount /mnt/nvd_data \
             --tmp-path=${{ runner.temp }}/blobfusetmp \
+            --container-name=${{ secrets.CONTAINER_NAME }}
+      - name: Unmount Azure Blob Storage
+        run: |
+          sudo umount /mnt/nvd_data || echo "Unmount failed"
