Using blobe test 2

diff --git a/.github/workflows/sonarqube.yml b/.github/workflows/sonarqube.yml
--- a/.github/workflows/sonarqube.yml
+++ b/.github/workflows/sonarqube.yml
@@ -26,6 +26,13 @@ jobs:
         run: |
           sudo apt update
           sudo apt install blobfuse2 fuse3 libfuse3-dev -y
+          echo "${{ secrets.CONFIG_CONTENT }}" > config.yaml
+          chmod 600 config.yaml
+          mkdir /home/runner/work/nvd_data
+          mkdir /home/runner/work/blobfusetmp
+
+      - name: Mount Azure Blob Storage
+        run: blobfuse2 mount /home/runner/work/nvd_data --config-file=config.yaml
 
       - name: Install Trivy
         run: |
@@ -35,7 +42,7 @@ jobs:
       - name: Set up Docker Buildx
         uses: docker/setup-buildx-action@v2
    
-      - name: Run OWASP
+      - name: Run OWASP Dependency Check
         run: |
           ${{ runner.temp }}/dependency-check/bin/dependency-check.sh --project "Test-ShopingKaro" \
             --out ${{ github.workspace }} \
@@ -75,3 +82,6 @@ jobs:
       #   timeout-minutes: 5
       #   env:
       #     SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
+
+      - name: Unmount Azure Blob Storage
+        run: sudo umount /mnt/nvd_data || echo "Unmount failed"
